name: hello world workflow

on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "hello-world"
        shell: bash
  good-bye:
    runs-on: ubuntu-22.04
    steps:
      - name: good bye
        run: echo "good bye"
        shell: bash
