name: hello world workflow

on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [12, 14, 16]
    
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "hello-world"
        shell: bash
  good-bye:
    runs-on: [self-hosted, linux]
    steps:
      - name: good bye
        run: echo "good bye"
        shell: bash
