name: Create a comment on new issues

on: 
  issues:
    types: [opened]
jobs:
  comment-wit-action:
    runs-on: ubuntu-22.04
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}'
        shell: bash
      
