name: Create a comment on new issues

on: 
  issues:
    types: [opened]
jobs:
  comment-wit-action:
    runs-on: [self-hosted,ununtu-latest]
    steps:
      - name: "dump github context"
        run: echo '${{ github.event.issue.number }}'
        shell: bash
      
