name: secrets
on:
  push:
    branches:
      - main
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Use Secret Token
        run: echo "Token is ${{ secrets.MY_SECRET_TOKEN }}"
